# python3
from typing import Any, List, AsyncIterator, Dict, Union

class Cursor:
    _rows: List[Any]
    async def execute(self, query: str, arg: Any = None) -> None: ...
    async def __aenter__(self) -> Any: ...
    async def __aexit__(self, *exc: object) -> None: ...
    def __aiter__(self) -> AsyncIterator[Dict[str, Union[int, str]]]: ... # White lies of typing...

class DictCursor(Cursor):
    ...
